// Shared decrypt runtime for gated interview-prep pages. Generated by
// scripts/build-prep.mjs — do not edit by hand.
(function () {
  const SALT = Uint8Array.from(atob("j83vJxpSb1/dunk14Fo4Mw=="), c => c.charCodeAt(0));
  const ITERATIONS = 600000;
  const STORE = "prep-key-v1";
  const fromB64 = s => Uint8Array.from(atob(s), c => c.charCodeAt(0));

  async function deriveKey(pin) {
    const material = await crypto.subtle.importKey(
      "raw", new TextEncoder().encode(pin), "PBKDF2", false, ["deriveKey"]);
    return crypto.subtle.deriveKey(
      { name: "PBKDF2", salt: SALT, iterations: ITERATIONS, hash: "SHA-256" },
      material, { name: "AES-GCM", length: 256 }, true, ["decrypt"]);
  }

  async function storedKey() {
    const raw = sessionStorage.getItem(STORE);
    if (!raw) return null;
    try {
      return await crypto.subtle.importKey(
        "raw", fromB64(raw), { name: "AES-GCM" }, true, ["decrypt"]);
    } catch { return null; }
  }

  async function rememberKey(key) {
    const raw = await crypto.subtle.exportKey("raw", key);
    sessionStorage.setItem(STORE, btoa(String.fromCharCode(...new Uint8Array(raw))));
  }

  async function decrypt(key, payload) {
    const pt = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: fromB64(payload.iv) }, key, fromB64(payload.ct));
    return new TextDecoder().decode(pt);
  }

  window.PrepCrypt = { deriveKey, storedKey, rememberKey, decrypt };
})();
